apiVersion: v1
kind: Service
metadata:
  name: {{ include "matter-temperature-sensor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matter-temperature-sensor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: matter
      protocol: TCP
      name: matter
  selector:
    {{- include "matter-temperature-sensor.selectorLabels" . | nindent 4 }}
